
interface _GlobalComponents {
      'CompaniesTable': typeof import("../components/CompaniesTable.vue")['default']
    'Logo': typeof import("../components/Logo.vue")['default']
    'AppCardsBars': typeof import("../components/app/cards/Bars.vue")['default']
    'AppCardsHistogram': typeof import("../components/app/cards/Histogram.vue")['default']
    'AppCardsLines': typeof import("../components/app/cards/Lines.vue")['default']
    'AppCardsSankey': typeof import("../components/app/cards/Sankey.vue")['default']
    'AppCardsTable': typeof import("../components/app/cards/Table.vue")['default']
    'AppChartsBars': typeof import("../components/app/charts/Bars.vue")['default']
    'AppChartsHistogram': typeof import("../components/app/charts/Histogram.vue")['default']
    'AppChartsLines': typeof import("../components/app/charts/Lines.vue")['default']
    'AppChartsSankey': typeof import("../components/app/charts/Sankey.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'Breadcrumb': typeof import("../components/ui/breadcrumb/index")['Breadcrumb']
    'BreadcrumbEllipsis': typeof import("../components/ui/breadcrumb/index")['BreadcrumbEllipsis']
    'BreadcrumbItem': typeof import("../components/ui/breadcrumb/index")['BreadcrumbItem']
    'BreadcrumbLink': typeof import("../components/ui/breadcrumb/index")['BreadcrumbLink']
    'BreadcrumbList': typeof import("../components/ui/breadcrumb/index")['BreadcrumbList']
    'BreadcrumbPage': typeof import("../components/ui/breadcrumb/index")['BreadcrumbPage']
    'BreadcrumbSeparator': typeof import("../components/ui/breadcrumb/index")['BreadcrumbSeparator']
    'Button': typeof import("../components/ui/button/index")['Button']
    'Calendar': typeof import("../components/ui/calendar/index")['Calendar']
    'CalendarCell': typeof import("../components/ui/calendar/index")['CalendarCell']
    'CalendarCellTrigger': typeof import("../components/ui/calendar/index")['CalendarCellTrigger']
    'CalendarGrid': typeof import("../components/ui/calendar/index")['CalendarGrid']
    'CalendarGridBody': typeof import("../components/ui/calendar/index")['CalendarGridBody']
    'CalendarGridHead': typeof import("../components/ui/calendar/index")['CalendarGridHead']
    'CalendarGridRow': typeof import("../components/ui/calendar/index")['CalendarGridRow']
    'CalendarHeadCell': typeof import("../components/ui/calendar/index")['CalendarHeadCell']
    'CalendarHeader': typeof import("../components/ui/calendar/index")['CalendarHeader']
    'CalendarHeading': typeof import("../components/ui/calendar/index")['CalendarHeading']
    'CalendarNextButton': typeof import("../components/ui/calendar/index")['CalendarNextButton']
    'CalendarPrevButton': typeof import("../components/ui/calendar/index")['CalendarPrevButton']
    'Card': typeof import("../components/ui/card/index")['Card']
    'CardHeader': typeof import("../components/ui/card/index")['CardHeader']
    'CardTitle': typeof import("../components/ui/card/index")['CardTitle']
    'CardDescription': typeof import("../components/ui/card/index")['CardDescription']
    'CardContent': typeof import("../components/ui/card/index")['CardContent']
    'CardFooter': typeof import("../components/ui/card/index")['CardFooter']
    'Checkbox': typeof import("../components/ui/checkbox/index")['Checkbox']
    'DropdownMenu': typeof import("../components/ui/dropdown-menu/index")['DropdownMenu']
    'DropdownMenuCheckboxItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
    'DropdownMenuContent': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuContent']
    'DropdownMenuGroup': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuGroup']
    'DropdownMenuItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuItem']
    'DropdownMenuLabel': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuLabel']
    'DropdownMenuRadioGroup': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
    'DropdownMenuRadioItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
    'DropdownMenuSeparator': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSeparator']
    'DropdownMenuShortcut': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuShortcut']
    'DropdownMenuSub': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSub']
    'DropdownMenuSubContent': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubContent']
    'DropdownMenuSubTrigger': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
    'DropdownMenuTrigger': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuTrigger']
    'DropdownMenuPortal': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuPortal']
    'Input': typeof import("../components/ui/input/index")['Input']
    'Label': typeof import("../components/ui/label/index")['Label']
    'Popover': typeof import("../components/ui/popover/index")['Popover']
    'PopoverContent': typeof import("../components/ui/popover/index")['PopoverContent']
    'PopoverTrigger': typeof import("../components/ui/popover/index")['PopoverTrigger']
    'Progress': typeof import("../components/ui/progress/index")['Progress']
    'Select': typeof import("../components/ui/select/index")['Select']
    'SelectValue': typeof import("../components/ui/select/index")['SelectValue']
    'SelectTrigger': typeof import("../components/ui/select/index")['SelectTrigger']
    'SelectContent': typeof import("../components/ui/select/index")['SelectContent']
    'SelectGroup': typeof import("../components/ui/select/index")['SelectGroup']
    'SelectItem': typeof import("../components/ui/select/index")['SelectItem']
    'SelectItemText': typeof import("../components/ui/select/index")['SelectItemText']
    'SelectLabel': typeof import("../components/ui/select/index")['SelectLabel']
    'SelectSeparator': typeof import("../components/ui/select/index")['SelectSeparator']
    'SelectScrollUpButton': typeof import("../components/ui/select/index")['SelectScrollUpButton']
    'SelectScrollDownButton': typeof import("../components/ui/select/index")['SelectScrollDownButton']
    'Separator': typeof import("../components/ui/separator/index")['Separator']
    'Sheet': typeof import("../components/ui/sheet/index")['Sheet']
    'SheetClose': typeof import("../components/ui/sheet/index")['SheetClose']
    'SheetContent': typeof import("../components/ui/sheet/index")['SheetContent']
    'SheetDescription': typeof import("../components/ui/sheet/index")['SheetDescription']
    'SheetFooter': typeof import("../components/ui/sheet/index")['SheetFooter']
    'SheetHeader': typeof import("../components/ui/sheet/index")['SheetHeader']
    'SheetTitle': typeof import("../components/ui/sheet/index")['SheetTitle']
    'SheetTrigger': typeof import("../components/ui/sheet/index")['SheetTrigger']
    'Sidebar': typeof import("../components/ui/sidebar/index")['Sidebar']
    'SidebarContent': typeof import("../components/ui/sidebar/index")['SidebarContent']
    'SidebarFooter': typeof import("../components/ui/sidebar/index")['SidebarFooter']
    'SidebarGroup': typeof import("../components/ui/sidebar/index")['SidebarGroup']
    'SidebarGroupAction': typeof import("../components/ui/sidebar/index")['SidebarGroupAction']
    'SidebarGroupContent': typeof import("../components/ui/sidebar/index")['SidebarGroupContent']
    'SidebarGroupLabel': typeof import("../components/ui/sidebar/index")['SidebarGroupLabel']
    'SidebarHeader': typeof import("../components/ui/sidebar/index")['SidebarHeader']
    'SidebarInput': typeof import("../components/ui/sidebar/index")['SidebarInput']
    'SidebarInset': typeof import("../components/ui/sidebar/index")['SidebarInset']
    'SidebarMenu': typeof import("../components/ui/sidebar/index")['SidebarMenu']
    'SidebarMenuAction': typeof import("../components/ui/sidebar/index")['SidebarMenuAction']
    'SidebarMenuBadge': typeof import("../components/ui/sidebar/index")['SidebarMenuBadge']
    'SidebarMenuButton': typeof import("../components/ui/sidebar/index")['SidebarMenuButton']
    'SidebarMenuItem': typeof import("../components/ui/sidebar/index")['SidebarMenuItem']
    'SidebarMenuSkeleton': typeof import("../components/ui/sidebar/index")['SidebarMenuSkeleton']
    'SidebarMenuSub': typeof import("../components/ui/sidebar/index")['SidebarMenuSub']
    'SidebarMenuSubButton': typeof import("../components/ui/sidebar/index")['SidebarMenuSubButton']
    'SidebarMenuSubItem': typeof import("../components/ui/sidebar/index")['SidebarMenuSubItem']
    'SidebarProvider': typeof import("../components/ui/sidebar/index")['SidebarProvider']
    'SidebarRail': typeof import("../components/ui/sidebar/index")['SidebarRail']
    'SidebarSeparator': typeof import("../components/ui/sidebar/index")['SidebarSeparator']
    'SidebarTrigger': typeof import("../components/ui/sidebar/index")['SidebarTrigger']
    'Skeleton': typeof import("../components/ui/skeleton/index")['Skeleton']
    'Slider': typeof import("../components/ui/slider/index")['Slider']
    'Stepper': typeof import("../components/ui/stepper/index")['Stepper']
    'StepperDescription': typeof import("../components/ui/stepper/index")['StepperDescription']
    'StepperIndicator': typeof import("../components/ui/stepper/index")['StepperIndicator']
    'StepperItem': typeof import("../components/ui/stepper/index")['StepperItem']
    'StepperSeparator': typeof import("../components/ui/stepper/index")['StepperSeparator']
    'StepperTitle': typeof import("../components/ui/stepper/index")['StepperTitle']
    'StepperTrigger': typeof import("../components/ui/stepper/index")['StepperTrigger']
    'Table': typeof import("../components/ui/table/index")['Table']
    'TableBody': typeof import("../components/ui/table/index")['TableBody']
    'TableCaption': typeof import("../components/ui/table/index")['TableCaption']
    'TableCell': typeof import("../components/ui/table/index")['TableCell']
    'TableEmpty': typeof import("../components/ui/table/index")['TableEmpty']
    'TableFooter': typeof import("../components/ui/table/index")['TableFooter']
    'TableHead': typeof import("../components/ui/table/index")['TableHead']
    'TableHeader': typeof import("../components/ui/table/index")['TableHeader']
    'TableRow': typeof import("../components/ui/table/index")['TableRow']
    'Tabs': typeof import("../components/ui/tabs/index")['Tabs']
    'TabsContent': typeof import("../components/ui/tabs/index")['TabsContent']
    'TabsList': typeof import("../components/ui/tabs/index")['TabsList']
    'TabsTrigger': typeof import("../components/ui/tabs/index")['TabsTrigger']
    'Textarea': typeof import("../components/ui/textarea/index")['Textarea']
    'Tooltip': typeof import("../components/ui/tooltip/index")['Tooltip']
    'TooltipContent': typeof import("../components/ui/tooltip/index")['TooltipContent']
    'TooltipProvider': typeof import("../components/ui/tooltip/index")['TooltipProvider']
    'TooltipTrigger': typeof import("../components/ui/tooltip/index")['TooltipTrigger']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
      'LazyCompaniesTable': typeof import("../components/CompaniesTable.vue")['default']
    'LazyLogo': typeof import("../components/Logo.vue")['default']
    'LazyAppCardsBars': typeof import("../components/app/cards/Bars.vue")['default']
    'LazyAppCardsHistogram': typeof import("../components/app/cards/Histogram.vue")['default']
    'LazyAppCardsLines': typeof import("../components/app/cards/Lines.vue")['default']
    'LazyAppCardsSankey': typeof import("../components/app/cards/Sankey.vue")['default']
    'LazyAppCardsTable': typeof import("../components/app/cards/Table.vue")['default']
    'LazyAppChartsBars': typeof import("../components/app/charts/Bars.vue")['default']
    'LazyAppChartsHistogram': typeof import("../components/app/charts/Histogram.vue")['default']
    'LazyAppChartsLines': typeof import("../components/app/charts/Lines.vue")['default']
    'LazyAppChartsSankey': typeof import("../components/app/charts/Sankey.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyBreadcrumb': typeof import("../components/ui/breadcrumb/index")['Breadcrumb']
    'LazyBreadcrumbEllipsis': typeof import("../components/ui/breadcrumb/index")['BreadcrumbEllipsis']
    'LazyBreadcrumbItem': typeof import("../components/ui/breadcrumb/index")['BreadcrumbItem']
    'LazyBreadcrumbLink': typeof import("../components/ui/breadcrumb/index")['BreadcrumbLink']
    'LazyBreadcrumbList': typeof import("../components/ui/breadcrumb/index")['BreadcrumbList']
    'LazyBreadcrumbPage': typeof import("../components/ui/breadcrumb/index")['BreadcrumbPage']
    'LazyBreadcrumbSeparator': typeof import("../components/ui/breadcrumb/index")['BreadcrumbSeparator']
    'LazyButton': typeof import("../components/ui/button/index")['Button']
    'LazyCalendar': typeof import("../components/ui/calendar/index")['Calendar']
    'LazyCalendarCell': typeof import("../components/ui/calendar/index")['CalendarCell']
    'LazyCalendarCellTrigger': typeof import("../components/ui/calendar/index")['CalendarCellTrigger']
    'LazyCalendarGrid': typeof import("../components/ui/calendar/index")['CalendarGrid']
    'LazyCalendarGridBody': typeof import("../components/ui/calendar/index")['CalendarGridBody']
    'LazyCalendarGridHead': typeof import("../components/ui/calendar/index")['CalendarGridHead']
    'LazyCalendarGridRow': typeof import("../components/ui/calendar/index")['CalendarGridRow']
    'LazyCalendarHeadCell': typeof import("../components/ui/calendar/index")['CalendarHeadCell']
    'LazyCalendarHeader': typeof import("../components/ui/calendar/index")['CalendarHeader']
    'LazyCalendarHeading': typeof import("../components/ui/calendar/index")['CalendarHeading']
    'LazyCalendarNextButton': typeof import("../components/ui/calendar/index")['CalendarNextButton']
    'LazyCalendarPrevButton': typeof import("../components/ui/calendar/index")['CalendarPrevButton']
    'LazyCard': typeof import("../components/ui/card/index")['Card']
    'LazyCardHeader': typeof import("../components/ui/card/index")['CardHeader']
    'LazyCardTitle': typeof import("../components/ui/card/index")['CardTitle']
    'LazyCardDescription': typeof import("../components/ui/card/index")['CardDescription']
    'LazyCardContent': typeof import("../components/ui/card/index")['CardContent']
    'LazyCardFooter': typeof import("../components/ui/card/index")['CardFooter']
    'LazyCheckbox': typeof import("../components/ui/checkbox/index")['Checkbox']
    'LazyDropdownMenu': typeof import("../components/ui/dropdown-menu/index")['DropdownMenu']
    'LazyDropdownMenuCheckboxItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
    'LazyDropdownMenuContent': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuContent']
    'LazyDropdownMenuGroup': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuGroup']
    'LazyDropdownMenuItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuItem']
    'LazyDropdownMenuLabel': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuLabel']
    'LazyDropdownMenuRadioGroup': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
    'LazyDropdownMenuRadioItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
    'LazyDropdownMenuSeparator': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSeparator']
    'LazyDropdownMenuShortcut': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuShortcut']
    'LazyDropdownMenuSub': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSub']
    'LazyDropdownMenuSubContent': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubContent']
    'LazyDropdownMenuSubTrigger': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
    'LazyDropdownMenuTrigger': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuTrigger']
    'LazyDropdownMenuPortal': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuPortal']
    'LazyInput': typeof import("../components/ui/input/index")['Input']
    'LazyLabel': typeof import("../components/ui/label/index")['Label']
    'LazyPopover': typeof import("../components/ui/popover/index")['Popover']
    'LazyPopoverContent': typeof import("../components/ui/popover/index")['PopoverContent']
    'LazyPopoverTrigger': typeof import("../components/ui/popover/index")['PopoverTrigger']
    'LazyProgress': typeof import("../components/ui/progress/index")['Progress']
    'LazySelect': typeof import("../components/ui/select/index")['Select']
    'LazySelectValue': typeof import("../components/ui/select/index")['SelectValue']
    'LazySelectTrigger': typeof import("../components/ui/select/index")['SelectTrigger']
    'LazySelectContent': typeof import("../components/ui/select/index")['SelectContent']
    'LazySelectGroup': typeof import("../components/ui/select/index")['SelectGroup']
    'LazySelectItem': typeof import("../components/ui/select/index")['SelectItem']
    'LazySelectItemText': typeof import("../components/ui/select/index")['SelectItemText']
    'LazySelectLabel': typeof import("../components/ui/select/index")['SelectLabel']
    'LazySelectSeparator': typeof import("../components/ui/select/index")['SelectSeparator']
    'LazySelectScrollUpButton': typeof import("../components/ui/select/index")['SelectScrollUpButton']
    'LazySelectScrollDownButton': typeof import("../components/ui/select/index")['SelectScrollDownButton']
    'LazySeparator': typeof import("../components/ui/separator/index")['Separator']
    'LazySheet': typeof import("../components/ui/sheet/index")['Sheet']
    'LazySheetClose': typeof import("../components/ui/sheet/index")['SheetClose']
    'LazySheetContent': typeof import("../components/ui/sheet/index")['SheetContent']
    'LazySheetDescription': typeof import("../components/ui/sheet/index")['SheetDescription']
    'LazySheetFooter': typeof import("../components/ui/sheet/index")['SheetFooter']
    'LazySheetHeader': typeof import("../components/ui/sheet/index")['SheetHeader']
    'LazySheetTitle': typeof import("../components/ui/sheet/index")['SheetTitle']
    'LazySheetTrigger': typeof import("../components/ui/sheet/index")['SheetTrigger']
    'LazySidebar': typeof import("../components/ui/sidebar/index")['Sidebar']
    'LazySidebarContent': typeof import("../components/ui/sidebar/index")['SidebarContent']
    'LazySidebarFooter': typeof import("../components/ui/sidebar/index")['SidebarFooter']
    'LazySidebarGroup': typeof import("../components/ui/sidebar/index")['SidebarGroup']
    'LazySidebarGroupAction': typeof import("../components/ui/sidebar/index")['SidebarGroupAction']
    'LazySidebarGroupContent': typeof import("../components/ui/sidebar/index")['SidebarGroupContent']
    'LazySidebarGroupLabel': typeof import("../components/ui/sidebar/index")['SidebarGroupLabel']
    'LazySidebarHeader': typeof import("../components/ui/sidebar/index")['SidebarHeader']
    'LazySidebarInput': typeof import("../components/ui/sidebar/index")['SidebarInput']
    'LazySidebarInset': typeof import("../components/ui/sidebar/index")['SidebarInset']
    'LazySidebarMenu': typeof import("../components/ui/sidebar/index")['SidebarMenu']
    'LazySidebarMenuAction': typeof import("../components/ui/sidebar/index")['SidebarMenuAction']
    'LazySidebarMenuBadge': typeof import("../components/ui/sidebar/index")['SidebarMenuBadge']
    'LazySidebarMenuButton': typeof import("../components/ui/sidebar/index")['SidebarMenuButton']
    'LazySidebarMenuItem': typeof import("../components/ui/sidebar/index")['SidebarMenuItem']
    'LazySidebarMenuSkeleton': typeof import("../components/ui/sidebar/index")['SidebarMenuSkeleton']
    'LazySidebarMenuSub': typeof import("../components/ui/sidebar/index")['SidebarMenuSub']
    'LazySidebarMenuSubButton': typeof import("../components/ui/sidebar/index")['SidebarMenuSubButton']
    'LazySidebarMenuSubItem': typeof import("../components/ui/sidebar/index")['SidebarMenuSubItem']
    'LazySidebarProvider': typeof import("../components/ui/sidebar/index")['SidebarProvider']
    'LazySidebarRail': typeof import("../components/ui/sidebar/index")['SidebarRail']
    'LazySidebarSeparator': typeof import("../components/ui/sidebar/index")['SidebarSeparator']
    'LazySidebarTrigger': typeof import("../components/ui/sidebar/index")['SidebarTrigger']
    'LazySkeleton': typeof import("../components/ui/skeleton/index")['Skeleton']
    'LazySlider': typeof import("../components/ui/slider/index")['Slider']
    'LazyStepper': typeof import("../components/ui/stepper/index")['Stepper']
    'LazyStepperDescription': typeof import("../components/ui/stepper/index")['StepperDescription']
    'LazyStepperIndicator': typeof import("../components/ui/stepper/index")['StepperIndicator']
    'LazyStepperItem': typeof import("../components/ui/stepper/index")['StepperItem']
    'LazyStepperSeparator': typeof import("../components/ui/stepper/index")['StepperSeparator']
    'LazyStepperTitle': typeof import("../components/ui/stepper/index")['StepperTitle']
    'LazyStepperTrigger': typeof import("../components/ui/stepper/index")['StepperTrigger']
    'LazyTable': typeof import("../components/ui/table/index")['Table']
    'LazyTableBody': typeof import("../components/ui/table/index")['TableBody']
    'LazyTableCaption': typeof import("../components/ui/table/index")['TableCaption']
    'LazyTableCell': typeof import("../components/ui/table/index")['TableCell']
    'LazyTableEmpty': typeof import("../components/ui/table/index")['TableEmpty']
    'LazyTableFooter': typeof import("../components/ui/table/index")['TableFooter']
    'LazyTableHead': typeof import("../components/ui/table/index")['TableHead']
    'LazyTableHeader': typeof import("../components/ui/table/index")['TableHeader']
    'LazyTableRow': typeof import("../components/ui/table/index")['TableRow']
    'LazyTabs': typeof import("../components/ui/tabs/index")['Tabs']
    'LazyTabsContent': typeof import("../components/ui/tabs/index")['TabsContent']
    'LazyTabsList': typeof import("../components/ui/tabs/index")['TabsList']
    'LazyTabsTrigger': typeof import("../components/ui/tabs/index")['TabsTrigger']
    'LazyTextarea': typeof import("../components/ui/textarea/index")['Textarea']
    'LazyTooltip': typeof import("../components/ui/tooltip/index")['Tooltip']
    'LazyTooltipContent': typeof import("../components/ui/tooltip/index")['TooltipContent']
    'LazyTooltipProvider': typeof import("../components/ui/tooltip/index")['TooltipProvider']
    'LazyTooltipTrigger': typeof import("../components/ui/tooltip/index")['TooltipTrigger']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const CompaniesTable: typeof import("../components/CompaniesTable.vue")['default']
export const Logo: typeof import("../components/Logo.vue")['default']
export const AppCardsBars: typeof import("../components/app/cards/Bars.vue")['default']
export const AppCardsHistogram: typeof import("../components/app/cards/Histogram.vue")['default']
export const AppCardsLines: typeof import("../components/app/cards/Lines.vue")['default']
export const AppCardsSankey: typeof import("../components/app/cards/Sankey.vue")['default']
export const AppCardsTable: typeof import("../components/app/cards/Table.vue")['default']
export const AppChartsBars: typeof import("../components/app/charts/Bars.vue")['default']
export const AppChartsHistogram: typeof import("../components/app/charts/Histogram.vue")['default']
export const AppChartsLines: typeof import("../components/app/charts/Lines.vue")['default']
export const AppChartsSankey: typeof import("../components/app/charts/Sankey.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const Breadcrumb: typeof import("../components/ui/breadcrumb/index")['Breadcrumb']
export const BreadcrumbEllipsis: typeof import("../components/ui/breadcrumb/index")['BreadcrumbEllipsis']
export const BreadcrumbItem: typeof import("../components/ui/breadcrumb/index")['BreadcrumbItem']
export const BreadcrumbLink: typeof import("../components/ui/breadcrumb/index")['BreadcrumbLink']
export const BreadcrumbList: typeof import("../components/ui/breadcrumb/index")['BreadcrumbList']
export const BreadcrumbPage: typeof import("../components/ui/breadcrumb/index")['BreadcrumbPage']
export const BreadcrumbSeparator: typeof import("../components/ui/breadcrumb/index")['BreadcrumbSeparator']
export const Button: typeof import("../components/ui/button/index")['Button']
export const Calendar: typeof import("../components/ui/calendar/index")['Calendar']
export const CalendarCell: typeof import("../components/ui/calendar/index")['CalendarCell']
export const CalendarCellTrigger: typeof import("../components/ui/calendar/index")['CalendarCellTrigger']
export const CalendarGrid: typeof import("../components/ui/calendar/index")['CalendarGrid']
export const CalendarGridBody: typeof import("../components/ui/calendar/index")['CalendarGridBody']
export const CalendarGridHead: typeof import("../components/ui/calendar/index")['CalendarGridHead']
export const CalendarGridRow: typeof import("../components/ui/calendar/index")['CalendarGridRow']
export const CalendarHeadCell: typeof import("../components/ui/calendar/index")['CalendarHeadCell']
export const CalendarHeader: typeof import("../components/ui/calendar/index")['CalendarHeader']
export const CalendarHeading: typeof import("../components/ui/calendar/index")['CalendarHeading']
export const CalendarNextButton: typeof import("../components/ui/calendar/index")['CalendarNextButton']
export const CalendarPrevButton: typeof import("../components/ui/calendar/index")['CalendarPrevButton']
export const Card: typeof import("../components/ui/card/index")['Card']
export const CardHeader: typeof import("../components/ui/card/index")['CardHeader']
export const CardTitle: typeof import("../components/ui/card/index")['CardTitle']
export const CardDescription: typeof import("../components/ui/card/index")['CardDescription']
export const CardContent: typeof import("../components/ui/card/index")['CardContent']
export const CardFooter: typeof import("../components/ui/card/index")['CardFooter']
export const Checkbox: typeof import("../components/ui/checkbox/index")['Checkbox']
export const DropdownMenu: typeof import("../components/ui/dropdown-menu/index")['DropdownMenu']
export const DropdownMenuCheckboxItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
export const DropdownMenuContent: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuContent']
export const DropdownMenuGroup: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuGroup']
export const DropdownMenuItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuItem']
export const DropdownMenuLabel: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuLabel']
export const DropdownMenuRadioGroup: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
export const DropdownMenuRadioItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
export const DropdownMenuSeparator: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSeparator']
export const DropdownMenuShortcut: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuShortcut']
export const DropdownMenuSub: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSub']
export const DropdownMenuSubContent: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubContent']
export const DropdownMenuSubTrigger: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
export const DropdownMenuTrigger: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuTrigger']
export const DropdownMenuPortal: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuPortal']
export const Input: typeof import("../components/ui/input/index")['Input']
export const Label: typeof import("../components/ui/label/index")['Label']
export const Popover: typeof import("../components/ui/popover/index")['Popover']
export const PopoverContent: typeof import("../components/ui/popover/index")['PopoverContent']
export const PopoverTrigger: typeof import("../components/ui/popover/index")['PopoverTrigger']
export const Progress: typeof import("../components/ui/progress/index")['Progress']
export const Select: typeof import("../components/ui/select/index")['Select']
export const SelectValue: typeof import("../components/ui/select/index")['SelectValue']
export const SelectTrigger: typeof import("../components/ui/select/index")['SelectTrigger']
export const SelectContent: typeof import("../components/ui/select/index")['SelectContent']
export const SelectGroup: typeof import("../components/ui/select/index")['SelectGroup']
export const SelectItem: typeof import("../components/ui/select/index")['SelectItem']
export const SelectItemText: typeof import("../components/ui/select/index")['SelectItemText']
export const SelectLabel: typeof import("../components/ui/select/index")['SelectLabel']
export const SelectSeparator: typeof import("../components/ui/select/index")['SelectSeparator']
export const SelectScrollUpButton: typeof import("../components/ui/select/index")['SelectScrollUpButton']
export const SelectScrollDownButton: typeof import("../components/ui/select/index")['SelectScrollDownButton']
export const Separator: typeof import("../components/ui/separator/index")['Separator']
export const Sheet: typeof import("../components/ui/sheet/index")['Sheet']
export const SheetClose: typeof import("../components/ui/sheet/index")['SheetClose']
export const SheetContent: typeof import("../components/ui/sheet/index")['SheetContent']
export const SheetDescription: typeof import("../components/ui/sheet/index")['SheetDescription']
export const SheetFooter: typeof import("../components/ui/sheet/index")['SheetFooter']
export const SheetHeader: typeof import("../components/ui/sheet/index")['SheetHeader']
export const SheetTitle: typeof import("../components/ui/sheet/index")['SheetTitle']
export const SheetTrigger: typeof import("../components/ui/sheet/index")['SheetTrigger']
export const Sidebar: typeof import("../components/ui/sidebar/index")['Sidebar']
export const SidebarContent: typeof import("../components/ui/sidebar/index")['SidebarContent']
export const SidebarFooter: typeof import("../components/ui/sidebar/index")['SidebarFooter']
export const SidebarGroup: typeof import("../components/ui/sidebar/index")['SidebarGroup']
export const SidebarGroupAction: typeof import("../components/ui/sidebar/index")['SidebarGroupAction']
export const SidebarGroupContent: typeof import("../components/ui/sidebar/index")['SidebarGroupContent']
export const SidebarGroupLabel: typeof import("../components/ui/sidebar/index")['SidebarGroupLabel']
export const SidebarHeader: typeof import("../components/ui/sidebar/index")['SidebarHeader']
export const SidebarInput: typeof import("../components/ui/sidebar/index")['SidebarInput']
export const SidebarInset: typeof import("../components/ui/sidebar/index")['SidebarInset']
export const SidebarMenu: typeof import("../components/ui/sidebar/index")['SidebarMenu']
export const SidebarMenuAction: typeof import("../components/ui/sidebar/index")['SidebarMenuAction']
export const SidebarMenuBadge: typeof import("../components/ui/sidebar/index")['SidebarMenuBadge']
export const SidebarMenuButton: typeof import("../components/ui/sidebar/index")['SidebarMenuButton']
export const SidebarMenuItem: typeof import("../components/ui/sidebar/index")['SidebarMenuItem']
export const SidebarMenuSkeleton: typeof import("../components/ui/sidebar/index")['SidebarMenuSkeleton']
export const SidebarMenuSub: typeof import("../components/ui/sidebar/index")['SidebarMenuSub']
export const SidebarMenuSubButton: typeof import("../components/ui/sidebar/index")['SidebarMenuSubButton']
export const SidebarMenuSubItem: typeof import("../components/ui/sidebar/index")['SidebarMenuSubItem']
export const SidebarProvider: typeof import("../components/ui/sidebar/index")['SidebarProvider']
export const SidebarRail: typeof import("../components/ui/sidebar/index")['SidebarRail']
export const SidebarSeparator: typeof import("../components/ui/sidebar/index")['SidebarSeparator']
export const SidebarTrigger: typeof import("../components/ui/sidebar/index")['SidebarTrigger']
export const Skeleton: typeof import("../components/ui/skeleton/index")['Skeleton']
export const Slider: typeof import("../components/ui/slider/index")['Slider']
export const Stepper: typeof import("../components/ui/stepper/index")['Stepper']
export const StepperDescription: typeof import("../components/ui/stepper/index")['StepperDescription']
export const StepperIndicator: typeof import("../components/ui/stepper/index")['StepperIndicator']
export const StepperItem: typeof import("../components/ui/stepper/index")['StepperItem']
export const StepperSeparator: typeof import("../components/ui/stepper/index")['StepperSeparator']
export const StepperTitle: typeof import("../components/ui/stepper/index")['StepperTitle']
export const StepperTrigger: typeof import("../components/ui/stepper/index")['StepperTrigger']
export const Table: typeof import("../components/ui/table/index")['Table']
export const TableBody: typeof import("../components/ui/table/index")['TableBody']
export const TableCaption: typeof import("../components/ui/table/index")['TableCaption']
export const TableCell: typeof import("../components/ui/table/index")['TableCell']
export const TableEmpty: typeof import("../components/ui/table/index")['TableEmpty']
export const TableFooter: typeof import("../components/ui/table/index")['TableFooter']
export const TableHead: typeof import("../components/ui/table/index")['TableHead']
export const TableHeader: typeof import("../components/ui/table/index")['TableHeader']
export const TableRow: typeof import("../components/ui/table/index")['TableRow']
export const Tabs: typeof import("../components/ui/tabs/index")['Tabs']
export const TabsContent: typeof import("../components/ui/tabs/index")['TabsContent']
export const TabsList: typeof import("../components/ui/tabs/index")['TabsList']
export const TabsTrigger: typeof import("../components/ui/tabs/index")['TabsTrigger']
export const Textarea: typeof import("../components/ui/textarea/index")['Textarea']
export const Tooltip: typeof import("../components/ui/tooltip/index")['Tooltip']
export const TooltipContent: typeof import("../components/ui/tooltip/index")['TooltipContent']
export const TooltipProvider: typeof import("../components/ui/tooltip/index")['TooltipProvider']
export const TooltipTrigger: typeof import("../components/ui/tooltip/index")['TooltipTrigger']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyCompaniesTable: typeof import("../components/CompaniesTable.vue")['default']
export const LazyLogo: typeof import("../components/Logo.vue")['default']
export const LazyAppCardsBars: typeof import("../components/app/cards/Bars.vue")['default']
export const LazyAppCardsHistogram: typeof import("../components/app/cards/Histogram.vue")['default']
export const LazyAppCardsLines: typeof import("../components/app/cards/Lines.vue")['default']
export const LazyAppCardsSankey: typeof import("../components/app/cards/Sankey.vue")['default']
export const LazyAppCardsTable: typeof import("../components/app/cards/Table.vue")['default']
export const LazyAppChartsBars: typeof import("../components/app/charts/Bars.vue")['default']
export const LazyAppChartsHistogram: typeof import("../components/app/charts/Histogram.vue")['default']
export const LazyAppChartsLines: typeof import("../components/app/charts/Lines.vue")['default']
export const LazyAppChartsSankey: typeof import("../components/app/charts/Sankey.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyBreadcrumb: typeof import("../components/ui/breadcrumb/index")['Breadcrumb']
export const LazyBreadcrumbEllipsis: typeof import("../components/ui/breadcrumb/index")['BreadcrumbEllipsis']
export const LazyBreadcrumbItem: typeof import("../components/ui/breadcrumb/index")['BreadcrumbItem']
export const LazyBreadcrumbLink: typeof import("../components/ui/breadcrumb/index")['BreadcrumbLink']
export const LazyBreadcrumbList: typeof import("../components/ui/breadcrumb/index")['BreadcrumbList']
export const LazyBreadcrumbPage: typeof import("../components/ui/breadcrumb/index")['BreadcrumbPage']
export const LazyBreadcrumbSeparator: typeof import("../components/ui/breadcrumb/index")['BreadcrumbSeparator']
export const LazyButton: typeof import("../components/ui/button/index")['Button']
export const LazyCalendar: typeof import("../components/ui/calendar/index")['Calendar']
export const LazyCalendarCell: typeof import("../components/ui/calendar/index")['CalendarCell']
export const LazyCalendarCellTrigger: typeof import("../components/ui/calendar/index")['CalendarCellTrigger']
export const LazyCalendarGrid: typeof import("../components/ui/calendar/index")['CalendarGrid']
export const LazyCalendarGridBody: typeof import("../components/ui/calendar/index")['CalendarGridBody']
export const LazyCalendarGridHead: typeof import("../components/ui/calendar/index")['CalendarGridHead']
export const LazyCalendarGridRow: typeof import("../components/ui/calendar/index")['CalendarGridRow']
export const LazyCalendarHeadCell: typeof import("../components/ui/calendar/index")['CalendarHeadCell']
export const LazyCalendarHeader: typeof import("../components/ui/calendar/index")['CalendarHeader']
export const LazyCalendarHeading: typeof import("../components/ui/calendar/index")['CalendarHeading']
export const LazyCalendarNextButton: typeof import("../components/ui/calendar/index")['CalendarNextButton']
export const LazyCalendarPrevButton: typeof import("../components/ui/calendar/index")['CalendarPrevButton']
export const LazyCard: typeof import("../components/ui/card/index")['Card']
export const LazyCardHeader: typeof import("../components/ui/card/index")['CardHeader']
export const LazyCardTitle: typeof import("../components/ui/card/index")['CardTitle']
export const LazyCardDescription: typeof import("../components/ui/card/index")['CardDescription']
export const LazyCardContent: typeof import("../components/ui/card/index")['CardContent']
export const LazyCardFooter: typeof import("../components/ui/card/index")['CardFooter']
export const LazyCheckbox: typeof import("../components/ui/checkbox/index")['Checkbox']
export const LazyDropdownMenu: typeof import("../components/ui/dropdown-menu/index")['DropdownMenu']
export const LazyDropdownMenuCheckboxItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
export const LazyDropdownMenuContent: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuContent']
export const LazyDropdownMenuGroup: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuGroup']
export const LazyDropdownMenuItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuItem']
export const LazyDropdownMenuLabel: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuLabel']
export const LazyDropdownMenuRadioGroup: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
export const LazyDropdownMenuRadioItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
export const LazyDropdownMenuSeparator: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSeparator']
export const LazyDropdownMenuShortcut: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuShortcut']
export const LazyDropdownMenuSub: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSub']
export const LazyDropdownMenuSubContent: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubContent']
export const LazyDropdownMenuSubTrigger: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
export const LazyDropdownMenuTrigger: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuTrigger']
export const LazyDropdownMenuPortal: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuPortal']
export const LazyInput: typeof import("../components/ui/input/index")['Input']
export const LazyLabel: typeof import("../components/ui/label/index")['Label']
export const LazyPopover: typeof import("../components/ui/popover/index")['Popover']
export const LazyPopoverContent: typeof import("../components/ui/popover/index")['PopoverContent']
export const LazyPopoverTrigger: typeof import("../components/ui/popover/index")['PopoverTrigger']
export const LazyProgress: typeof import("../components/ui/progress/index")['Progress']
export const LazySelect: typeof import("../components/ui/select/index")['Select']
export const LazySelectValue: typeof import("../components/ui/select/index")['SelectValue']
export const LazySelectTrigger: typeof import("../components/ui/select/index")['SelectTrigger']
export const LazySelectContent: typeof import("../components/ui/select/index")['SelectContent']
export const LazySelectGroup: typeof import("../components/ui/select/index")['SelectGroup']
export const LazySelectItem: typeof import("../components/ui/select/index")['SelectItem']
export const LazySelectItemText: typeof import("../components/ui/select/index")['SelectItemText']
export const LazySelectLabel: typeof import("../components/ui/select/index")['SelectLabel']
export const LazySelectSeparator: typeof import("../components/ui/select/index")['SelectSeparator']
export const LazySelectScrollUpButton: typeof import("../components/ui/select/index")['SelectScrollUpButton']
export const LazySelectScrollDownButton: typeof import("../components/ui/select/index")['SelectScrollDownButton']
export const LazySeparator: typeof import("../components/ui/separator/index")['Separator']
export const LazySheet: typeof import("../components/ui/sheet/index")['Sheet']
export const LazySheetClose: typeof import("../components/ui/sheet/index")['SheetClose']
export const LazySheetContent: typeof import("../components/ui/sheet/index")['SheetContent']
export const LazySheetDescription: typeof import("../components/ui/sheet/index")['SheetDescription']
export const LazySheetFooter: typeof import("../components/ui/sheet/index")['SheetFooter']
export const LazySheetHeader: typeof import("../components/ui/sheet/index")['SheetHeader']
export const LazySheetTitle: typeof import("../components/ui/sheet/index")['SheetTitle']
export const LazySheetTrigger: typeof import("../components/ui/sheet/index")['SheetTrigger']
export const LazySidebar: typeof import("../components/ui/sidebar/index")['Sidebar']
export const LazySidebarContent: typeof import("../components/ui/sidebar/index")['SidebarContent']
export const LazySidebarFooter: typeof import("../components/ui/sidebar/index")['SidebarFooter']
export const LazySidebarGroup: typeof import("../components/ui/sidebar/index")['SidebarGroup']
export const LazySidebarGroupAction: typeof import("../components/ui/sidebar/index")['SidebarGroupAction']
export const LazySidebarGroupContent: typeof import("../components/ui/sidebar/index")['SidebarGroupContent']
export const LazySidebarGroupLabel: typeof import("../components/ui/sidebar/index")['SidebarGroupLabel']
export const LazySidebarHeader: typeof import("../components/ui/sidebar/index")['SidebarHeader']
export const LazySidebarInput: typeof import("../components/ui/sidebar/index")['SidebarInput']
export const LazySidebarInset: typeof import("../components/ui/sidebar/index")['SidebarInset']
export const LazySidebarMenu: typeof import("../components/ui/sidebar/index")['SidebarMenu']
export const LazySidebarMenuAction: typeof import("../components/ui/sidebar/index")['SidebarMenuAction']
export const LazySidebarMenuBadge: typeof import("../components/ui/sidebar/index")['SidebarMenuBadge']
export const LazySidebarMenuButton: typeof import("../components/ui/sidebar/index")['SidebarMenuButton']
export const LazySidebarMenuItem: typeof import("../components/ui/sidebar/index")['SidebarMenuItem']
export const LazySidebarMenuSkeleton: typeof import("../components/ui/sidebar/index")['SidebarMenuSkeleton']
export const LazySidebarMenuSub: typeof import("../components/ui/sidebar/index")['SidebarMenuSub']
export const LazySidebarMenuSubButton: typeof import("../components/ui/sidebar/index")['SidebarMenuSubButton']
export const LazySidebarMenuSubItem: typeof import("../components/ui/sidebar/index")['SidebarMenuSubItem']
export const LazySidebarProvider: typeof import("../components/ui/sidebar/index")['SidebarProvider']
export const LazySidebarRail: typeof import("../components/ui/sidebar/index")['SidebarRail']
export const LazySidebarSeparator: typeof import("../components/ui/sidebar/index")['SidebarSeparator']
export const LazySidebarTrigger: typeof import("../components/ui/sidebar/index")['SidebarTrigger']
export const LazySkeleton: typeof import("../components/ui/skeleton/index")['Skeleton']
export const LazySlider: typeof import("../components/ui/slider/index")['Slider']
export const LazyStepper: typeof import("../components/ui/stepper/index")['Stepper']
export const LazyStepperDescription: typeof import("../components/ui/stepper/index")['StepperDescription']
export const LazyStepperIndicator: typeof import("../components/ui/stepper/index")['StepperIndicator']
export const LazyStepperItem: typeof import("../components/ui/stepper/index")['StepperItem']
export const LazyStepperSeparator: typeof import("../components/ui/stepper/index")['StepperSeparator']
export const LazyStepperTitle: typeof import("../components/ui/stepper/index")['StepperTitle']
export const LazyStepperTrigger: typeof import("../components/ui/stepper/index")['StepperTrigger']
export const LazyTable: typeof import("../components/ui/table/index")['Table']
export const LazyTableBody: typeof import("../components/ui/table/index")['TableBody']
export const LazyTableCaption: typeof import("../components/ui/table/index")['TableCaption']
export const LazyTableCell: typeof import("../components/ui/table/index")['TableCell']
export const LazyTableEmpty: typeof import("../components/ui/table/index")['TableEmpty']
export const LazyTableFooter: typeof import("../components/ui/table/index")['TableFooter']
export const LazyTableHead: typeof import("../components/ui/table/index")['TableHead']
export const LazyTableHeader: typeof import("../components/ui/table/index")['TableHeader']
export const LazyTableRow: typeof import("../components/ui/table/index")['TableRow']
export const LazyTabs: typeof import("../components/ui/tabs/index")['Tabs']
export const LazyTabsContent: typeof import("../components/ui/tabs/index")['TabsContent']
export const LazyTabsList: typeof import("../components/ui/tabs/index")['TabsList']
export const LazyTabsTrigger: typeof import("../components/ui/tabs/index")['TabsTrigger']
export const LazyTextarea: typeof import("../components/ui/textarea/index")['Textarea']
export const LazyTooltip: typeof import("../components/ui/tooltip/index")['Tooltip']
export const LazyTooltipContent: typeof import("../components/ui/tooltip/index")['TooltipContent']
export const LazyTooltipProvider: typeof import("../components/ui/tooltip/index")['TooltipProvider']
export const LazyTooltipTrigger: typeof import("../components/ui/tooltip/index")['TooltipTrigger']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']

export const componentNames: string[]
