// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/16/2025, 11:30:45 AM
const configMerger = require("/Users/maxime/Documents/ddvc/front/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/Users/maxime/Documents/ddvc/front/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/maxime/Documents/ddvc/front/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/maxime/Documents/ddvc/front/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/maxime/Documents/ddvc/front/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/maxime/Documents/ddvc/front/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/maxime/Documents/ddvc/front/plugins/**/*.{js,ts,mjs}","/Users/maxime/Documents/ddvc/front/composables/**/*.{js,ts,mjs}","/Users/maxime/Documents/ddvc/front/utils/**/*.{js,ts,mjs}","/Users/maxime/Documents/ddvc/front/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/maxime/Documents/ddvc/front/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/maxime/Documents/ddvc/front/app.config.{js,ts,mjs}"] } }));

module.exports = config
